name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RALS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
      - name: Setup database
        run: bundle exec rails db:create db:migrate
      - name: Run rspec
        run: bundle exec rspec
      - name: Run rubocop
        run: bundle exec rubocop
